events {
  worker_connections 1024;
}

http {
  upstream orders {
    server orders-service:3001;
  }
  upstream payments {
    server payments-service:3002;
  }
  upstream inventory {
    server inventory-service:3003;
  }

  server {
    listen 80;

    proxy_pass_request_headers on;

    location /api/orders {
      proxy_pass http://orders;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/payments {
      proxy_pass http://payments;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/inventory {
      proxy_pass http://inventory;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
      return 200 '{"status":"ok"}';
      add_header Content-Type application/json;
    }
  }
}