apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: pedidos-veloz
data:
  NODE_ENV: "production"
  PORT: "3001"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  LOG_LEVEL: "info"
  OTEL_SERVICE_NAME: "orders-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: pedidos-veloz
data:
  NODE_ENV: "production"
  PORT: "3002"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  LOG_LEVEL: "info"
  OTEL_SERVICE_NAME: "payments-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: pedidos-veloz
data:
  NODE_ENV: "production"
  PORT: "3003"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  LOG_LEVEL: "info"
  OTEL_SERVICE_NAME: "inventory-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318"
