name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Lint e Testes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [orders-service, payments-service, inventory-service]

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install
        working-directory: services/${{ matrix.service }}

      - name: Lint
        run: npm run lint
        working-directory: services/${{ matrix.service }}

      - name: Testes
        run: npm test
        working-directory: services/${{ matrix.service }}

  build-check:
    name: Validar build Docker
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service:
          [api-gateway, orders-service, payments-service, inventory-service]

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Build da imagem
        run: |
          docker build \
            --tag ${{ matrix.service }}:${{ github.sha }} \
            ./services/${{ matrix.service }}
